[package]
name = "api"
version = "0.1.0"
authors = ["Meteor <bobogei81123@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dependencies.uuid]
version = "0.8"
features = ["serde"]
